FROM nginx:latest

# Создание SSL сертификатов для разработки
RUN mkdir /etc/nginx/ssl
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/server.key \
    -out /etc/nginx/ssl/server.crt \
    -subj "/C=RU/ST=Moscow/L=Moscow/O=Development/CN=localhost"

RUN chmod 600 /etc/nginx/ssl/server.key && chmod 644 /etc/nginx/ssl/server.crt

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
